In [28]:
import pandas as pd
df = pd.read_csv(r"<file_path>.csv", encoding = 'utf-8')
df.head(10)

,sIP,dIP,sPort,dPort,proto,packets,bytes,flags,duration
0,3232249961,3232249960,33968,443,6,7,919,27,0.122
1,3232249960,3232249961,443,33968,6,4,1766,27,0.121
2,3232249961,3232249960,33970,443,6,7,919,27,0.120
3,3232249960,3232249961,443,33970,6,4,1766,27,0.118
4,3232249961,3232249960,33972,443,6,7,919,27,0.005
5,3232249960,3232249961,443,33972,6,4,1766,27,0.005
6,3232249961,3232249960,33974,443,6,7,919,27,0.006
7,3232249960,3232249961,443,33974,6,4,1766,27,0.006
8,3232249961,3232249960,33978,443,6,6,905,27,0.008
9,3232249960,3232249961,443,33978,6,5,508,27,0.008

In [29]:
import numpy as np
from sklearn.cluster import MeanShift, estimate_bandwidth
from sklearn.datasets import make_blobs

X = df
bandwidth = estimate_bandwidth(X, quantile=0.2, n_samples=500)

# Fit Mean Shift with Scikit
meanshift = MeanShift(bandwidth=bandwidth)
meanshift.fit(X)
labels = meanshift.labels_
labels_unique = np.unique(labels)
n_clusters_ = len(labels_unique)
cluster_centers = meanshift.cluster_centers_

print("Clusters found: %d" % n_clusters_)
print (np.unique(labels, return_counts=True))
# print(cluster_centers)
# Predict the cluster for all the samples
P = meanshift.predict(X)

Clusters found: 3
(array([0, 1, 2]), array([873,   8,   2]))

In [31]:
# Para juntar o label ao dateset original
df["Cluster"]=labels
# Para ver as linhas do cluster -1
df[df.Cluster == 1]

,sIP,dIP,sPort,dPort,proto,packets,bytes,flags,duration,Cluster
579,3232249961,4026531834,58862,1900,17,4,780,0,3.005,1
771,3232249961,4026531834,54363,1900,17,4,780,0,3.045,1
807,3232249961,4026531834,34980,1900,17,4,780,0,3.006,1
866,3232249961,4026531834,33542,1900,17,4,780,0,3.018,1
868,3232249961,4026531834,40092,1900,17,4,780,0,3.005,1
876,3232249961,4026531834,45313,1900,17,4,780,0,3.028,1
877,3232249961,4026531834,52313,1900,17,4,780,0,3.003,1
882,3232249961,4026531834,40692,1900,17,4,780,0,3.009,1